### ISSUE TITLE
Stuck on searching for new version 

### ISSUE THREAD

**Issue by acostaf** [Anifacted/lerna-update-wizard#25] opened 2018-09-13 13:01 UTC
Lerna Update Wizard v0.9.3                             

Getting this at the beginning of the process
Starting update wizard for root                                      
                                                                     
? Select a dependency to upgrade: (Use arrow keys or type to search) 
> @nestjs/common (2 versions)      

On selecting the first one, the system get stuck on that screen, cannot even exit using Control C           

? Select a dependency to upgrade: @nestjs/common(2 versions)

**Comment by Anifacted** [comment] 2018-09-13 16:17
Hmm, that sounds strange. It can get stuck if there's an unhandled exception occasionally, but then the error message will be revealed when exiting the script (CTRL+C).
Let me try to reproduce the issue...

**Comment by Anifacted** [comment] 2018-09-13 18:50
Does this only happen with the `@nestjs/common` dependency or have you experienced it with others too?

Maybe it is something related to the target package (your Lerna sub-package). Can you successfully upgrade/add other dependencies to this same package that contains the `@nestjs/common` dependency?

**Comment by Anifacted** [comment] 2018-09-14 10:01
@acostaf, I pushed some changes to make error-handling better. If an error occurs behind the scenes and you are being prevented from seeing it because of the script getting stuck, `0.9.4` will hopefully solve this, as it now kills the process and logs any error before things get stuck.

Could you give it another go with this version?

**Comment by Anifacted** [comment] 2018-12-03 16:32
Closing this. If an error occurs in newer versions, the error message will be shown, rather than the process just seeming to be stuck, so we should be able to open a new issue if the problem persists.

**Closed by Anifacted** 2018-12-03 16:32 UTC
